name: build deb
run-name: Github Action is building Debian Packages
on: [push]
jobs: 
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout dtkcore
              uses: actions/checkout@v3
              with: 
                repository: linuxdeepin/dtkcore
            - name: Build and Install dtkcore
              run: |
                  cd ${{ github.workspace }}/dtkcore
                  sudo apt build-dep .
                  cmake -B build
                  cmake --build build -j $(nproc)
                  sudo dpkg-buildpackage -us -uc -b
                  cd ../
                  sudo apt install ./*.deb
