name: build deb
run-name: Github Action is building Debian Packages
on: [push]
jobs: 
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout dtkcore
              uses: actions/checkout@v3
              with: 
                repository: linuxdeepin/dtkcore
                
            - name: Build and Install dtkcommon
              run: |
                  git clone https://github.com/linuxdeepin/dtkcommon.git
                  cd dtkcommon
                  sudo apt build-dep .
                  cmake -B build
                  cmake --build build -j $(nproc)
                  sudo dpkg-buildpackage -us -uc -b
                  cd ../
                  sudo apt install ./*.deb
                  
            - name: Build and Install dtkcore
              run: |
                  git clone https://github.com/linuxdeepin/dtkcore.git
                  cd dtkcore
                  sudo apt build-dep .
                  cmake -B build
                  cmake --build build -j $(nproc)
                  sudo dpkg-buildpackage -us -uc -b
                  cd ../
                  sudo apt install ./*.deb

            - name: Build and Install dtkgui
              run: |
                  git clone https://github.com/linuxdeepin/dtkgui.git
                  cd dtkgui
                  sudo apt build-dep .
                  cmake -B build
                  cmake --build build -j $(nproc)
                  sudo dpkg-buildpackage -us -uc -b
                  cd ../
                  sudo apt install ./*.deb
                  
            - name: Build and Install dtkwidget
              run: |
                  git clone https://github.com/linuxdeepin/dtkwidget.git
                  cd dtkwidget
                  sudo apt build-dep .
                  cmake -B build
                  cmake --build build -j $(nproc)
                  sudo dpkg-buildpackage -us -uc -b
                  cd ../
                  sudo apt install ./*.deb

            - name: Build and Install dtkdeclarative
              run: |
                  git clone https://github.com/linuxdeepin/dtkdeclarative.git
                  cd dtkdeclarative
                  sudo apt build-dep .
                  cmake -B build
                  cmake --build build -j $(nproc)
                  sudo dpkg-buildpackage -us -uc -b
                  cd ../
                  sudo apt install ./*.deb
