name: build deb
run-name: Github Action is building Debian Packages
on: [push]
jobs: 
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Add Deepin source
              run: |
                  echo "deb https://proposed-packages.deepin.com/beige-testing/ unstable main dde commercial community" | sudo tee /etc/apt/sources.list.d/deepin-unstable-source.list
                  echo "deb https://community-packages.deepin.com/beige/ beige main commercial community" | sudo tee -a /etc/apt/sources.list

            - name: Cat sources
              run: |
                    sudo cat /etc/apt/sources.list
                    sudo cat /etc/apt/sources.list.d/deepin-unstable-source.list

            - name: Update System
              run: |
                  sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 425956BB3E31DF51
                  sudo apt update
                  sudo apt install libdtkcore-dev
