name: build deb
run-name: Github Action is building Debian Packages
on: [push]
jobs: 
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Add Deepin source
              run: |
                  echo "deb https://proposed-packages.deepin.com/beige-testing/ unstable main dde commercial community" | tee /etc/apt/sources.list.d/deepin-unstable-source.list
                  echo "\ndeb https://community-packages.deepin.com/beige/ beige main commercial community" >> /etc/apt/sources.list

            - name: Cat sources
              run: |
                    cat /etc/apt/sources.list
                    cat /etc/apt/sources.list.d/deepin-unstable-source.list
