name: Deploy Hugo Site

on:
  push:
    branches:
      - master # 修改为你的主分支名称

permissions: 
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: student-ice.github.io
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest' # 可以指定特定的 Hugo 版本

      - name: Build
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
